# Generated by Django 4.2 on 2023-04-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('C', 'comment'), ('SSC', 'system staff confirm'), ('F', 'follow'), ('U', 'unfollow')], max_length=50),
        ),
    ]
