# Generated by Django 4.2 on 2023-04-14 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('notification', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='activity_notify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_notify', to='activity.activity'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('C', 'comment'), ('Fav', 'favourite'), ('SSC', 'system staff confirm'), ('F', 'follow'), ('U', 'unfollow')], max_length=50),
        ),
    ]
