# Generated by Django 4.2 on 2023-06-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('C', 'comment'), ('AA', 'activity accept'), ('AR', 'activity reject'), ('AJ', 'activity join'), ('AU', 'activity unjoin'), ('Fav', 'favourite'), ('SSC', 'system staff confirm'), ('F', 'follow'), ('U', 'unfollow')], max_length=50),
        ),
    ]
