# Generated by Django 4.2 on 2023-06-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_myuser_first_name_alter_myuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='secret_answer',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='secret_question',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
