# Generated by Django 4.2 on 2023-06-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_myuser_secret_answer_myuser_secret_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='secret_answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='secret_question',
            field=models.CharField(max_length=100),
        ),
    ]
