# Generated by Django 4.2 on 2023-06-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_myuser_secret_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('FRIEND', 'Friend'), ('COMPANY_STAFF', 'Company_Staff'), ('SYSTEM_STAFF', 'System_Staff')], default='FRIEND', max_length=50),
        ),
    ]
