# Generated by Django 4.2 on 2023-06-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_myuser_secret_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='secret_question',
            field=models.CharField(choices=[('1', 'What is your favorite color?'), ('2', 'What is your favorite animal?'), ('3', 'What is your favorite food?')], max_length=100),
        ),
    ]
