# Generated by Django 4.2 on 2023-04-20 14:35

import advertisement.models
import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Travel", "TRAVEL"),
                            ("Cinema", "CINEMA"),
                            ("Theatre", "THEATRE"),
                            ("Sport", "SPORT"),
                            ("Culture", "CULTURE"),
                            ("Music", "MUSIC"),
                            ("Game", "GAME"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=advertisement.models.advertisement_file_directory_path,
                    ),
                ),
                ("total_user_count", models.IntegerField(blank=True, null=True)),
                (
                    "advertisement_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("advertisement_status", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                (
                    "advertisement_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "advertisement_company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="address.address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertisement",
                "verbose_name_plural": "Advertisements",
                "db_table": "advertisement",
                "ordering": ("-created_at",),
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
    ]
