# Generated by Django 4.2 on 2023-04-20 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_activity_options_alter_activity_table'),
        ('comment', '0002_remove_comment_user_id_comment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='activity_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='activity.activity'),
        ),
    ]
