# Generated by Django 4.2 on 2023-04-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_alter_activity_address'),
        ('comment', '0005_remove_comment_activity_comment_activity_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='activity_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_id', to='activity.activity'),
        ),
    ]
