# Generated by Django 4.2 on 2023-05-22 16:07

import comment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_remove_comment_activity_comment_comment_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=comment.models.comment_file_directory_path),
        ),
    ]
