# Generated by Django 4.2 on 2023-05-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
