# Generated by Django 4.2 on 2023-04-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Sport', 'SPORT'), ('Culture', 'CULTURE'), ('Music', 'MUSIC'), ('Game', 'GAME'), ('Travel', 'TRAVEL'), ('Cinema', 'CINEMA'), ('Theatre', 'THEATRE')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
