# Generated by Django 4.2 on 2023-04-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0003_alter_activity_category_delete_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activityuser",
            old_name="status",
            new_name="participate_status",
        ),
    ]
