# Generated by Django 4.2 on 2023-04-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_rename_status_activityuser_participate_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-created_at',)},
        ),
    ]
