# Generated by Django 4.2 on 2023-04-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-created_at',), 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
    ]
