# Generated by Django 4.2 on 2023-04-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('activity', '0006_alter_activity_options_alter_activity_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
