# Generated by Django 4.2 on 2023-04-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('activity', '0012_alter_activity_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='address.address'),
        ),
    ]
