# Generated by Django 4.2 on 2023-04-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_alter_activity_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='total_player_count',
            field=models.IntegerField(null=True),
        ),
    ]
