# Generated by Django 4.2 on 2023-05-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('activity', '0015_alter_activity_total_player_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='address.address'),
        ),
    ]
